### PR TITLE
sync/atomic -> uber/atomic

### PR DESCRIPTION
**Pull request by boks1971**

### CODE REVIEW

**Comment by davidzhao** [comment]
since the core loop had changed in the other PR, I'll merge that one in first and we can transition to uber/atomic afterwards.

**Comment by boks1971** [comment]
Sure @davidzhao . I will rebase.

**Comment by boks1971** [comment]
Merged with main and resolved conflicts. Please have a look when you get a chance.

**Review by davidzhao — APPROVED** [review]
looks good!

**Pull request merged**
